[package]
name = "tpi"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
authors = ["Sven Rademakers <sven@turingpi.com>"]
description = "CLI tool to control a Turing-Pi board"
homepage = "https://turingpi.com/"
repository = "https://github.com/turing-machines/tpi"

[dependencies]
anyhow = "1.0.75"
bytes = "1.4.0"
clap = { version = "4.4.2", features = ["derive"] }
clap_complete = "4.4.0"
log = "0.4.20"
reqwest = { version = "0.11.20", default-features = false, features = ["gzip",
"json", "rustls-tls" ] }
serde_json = "1.0.105"
tokio = { version = "1.32.0", features = ["rt", "rt-multi-thread", "macros", "fs"] }
url = "2.4.1"

[features]
local-only= []
